#!/bin/csh
MSTL_LOC = /physics/jpknelle/mstl
NULIB_LOC = /physics/sricher/NuLib
HDF5_LOC = /physics/sricher/hdf5-1.10.1/hdf5_gnu

INCLUDE  = -I${MSTL_LOC}/include/ -I${MSTL_LOC}/include/physics/ -I${MSTL_LOC}/include/math2/ -I${MSTL_LOC}/include/math2/algebra -I${MSTL_LOC}/include/math2/analysis -I${MSTL_LOC}/include/math2/data -I${MSTL_LOC}/include/math2/geometry -I${MSTL_LOC}/include/math2/group -I${MSTL_LOC}/include/math2/spline -I"${MSTL_LOC}/include/math2/probability and statistics" -I${HDF5_LOC}/include

LIBRARY = -L${MSTL_LOC}/lib/ -lmstl.g++ ${NULIB_LOC}/src/nulib.a -L${HDF5_LOC}/lib -lhdf5 -lhdf5_fortran -lhdf5_cpp -lgfortran

WHICHCODE = sqa2.psma

COMP = g++ -fopenmp -g -funit-at-a-time -funroll-loops -std=gnu++0x -O3

${WHICHCODE}.o: ${WHICHCODE}.cpp
	${COMP} ${WHICHCODE}.cpp -o ${WHICHCODE}.x ${INCLUDE} ${LIBRARY}
