#!/bin/csh

MSTL_LOC = /physics/jpknelle/mstl

INCLUDE  = -I${MSTL_LOC}/include/ -I${MSTL_LOC}/include/physics/ -I${MSTL_LOC}/include/math2/ -I${MSTL_LOC}/include/math2/algebra -I${MSTL_LOC}/include/math2/analysis -I${MSTL_LOC}/include/math2/data -I${MSTL_LOC}/include/math2/geometry -I${MSTL_LOC}/include/math2/group -I${MSTL_LOC}/include/math2/spline -I"${MSTL_LOC}/include/math2/probability and statistics"

LIBRARY = -L${MSTL_LOC}/lib/

WHICHCODE = sqa2.psma

COMP = g++ ${INCLUDE} ${LIBRARY} 

OPTIONS = -O -lmstl.g++ -fopenmp -pg -g -O3 -funit-at-a-time -funroll-loops -std=gnu++0x 

${WHICHCODE}.o: ${WHICHCODE}.cpp
	${COMP} ${INCLUDE} ${LIBRARY} ${WHICHCODE}.cpp -o ${WHICHCODE}.x ${OPTIONS}
